version: '2.0'
services:
  fe:
    image: "yourdockerimagehere"
    expose:
      - port: 80
        as: 80
        accept:
          - sdxl.akash.network
        to:
          - global: true
profiles:
  compute:
    fe:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          - size: 1Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
          - akash18qa2a2ltfyvkyj0ggj3hkvuj6twzyumuaru9s4
      pricing:
        fe:
          denom: uakt
          amount: 10000
deployment:
  fe:
    akash:
      profile: fe
      count: 1
