---
version: "2.0"
services:
  ws:
    image: "yourdockerimagehere"
    expose:
      - port: 3001
        as: 8000
        to:
          - global: true
    env:
      - LOG_DB_HOST=
      - LOG_DB_PORT=
      - LOG_DB_NAME=
      - LOG_DB_USER=
      - LOG_DB_PASSWORD=
      - SERVER_NAME=
      - "APIURL="
profiles:
  compute:
    ws:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          - size: 1Gi
  placement:
    dcloud:
      pricing:
        ws:
          denom: uakt
          amount: 1000
deployment:
  ws:
    dcloud:
      profile: ws
      count: 1
